"""Verify Aurora Tech L28 weekly progress report (xlsx) generated by openpyxl."""
import os
from datetime import datetime

import openpyxl

OUTPUT = r'c:\Users\59620\.claude\skills\tendo-brand\test\TendoCN - Aurora Tech Shanghai - L28 Smart Office Retrofit Weekly Progress Report (项目周报) 2026-07-30.xlsx'

EXPECTED_PHASES = ['Cable Pulling', 'Termination', 'Faceplate Installation', 'Testing']
EXPECTED_SUBS = ['Reception', 'Open Office', 'Meeting Room']

STATUS_COLOR = {
    'In Progress': 'FF00B050',
    'Delay':       'FFFF0000',
    'Not Started': 'FFFFC000',
    'Completed':   'FF000000',
}

EXPECTED_PROGRESS = {
    'Reception': {
        'Cable Pulling':          (1.00, 'Completed'),
        'Termination':            (0.80, 'In Progress'),
        'Faceplate Installation': (0.50, 'In Progress'),
        'Testing':                (0.00, 'Not Started'),
    },
    'Open Office': {
        'Cable Pulling':          (0.80, 'In Progress'),
        'Termination':            (0.30, 'In Progress'),
        'Faceplate Installation': (0.00, 'Not Started'),
        'Testing':                (0.00, 'Not Started'),
    },
    'Meeting Room': {
        'Cable Pulling':          (0.20, 'Delay'),
        'Termination':            (0.00, 'Not Started'),
        'Faceplate Installation': (0.00, 'Not Started'),
        'Testing':                (0.00, 'Not Started'),
    },
}

EXPECTED_DATES = {
    'Reception': {
        'Cable Pulling':          ('2026-07-25', '2026-07-25'),
        'Termination':            ('2026-07-28', '2026-07-30'),
        'Faceplate Installation': ('2026-07-29', '2026-07-31'),
        'Testing':                (None,         '2026-08-02'),
    },
    'Open Office': {
        'Cable Pulling':          ('2026-07-28', '2026-07-30'),
        'Termination':            ('2026-07-29', '2026-08-01'),
        'Faceplate Installation': (None,         '2026-08-03'),
        'Testing':                (None,         '2026-08-05'),
    },
    'Meeting Room': {
        'Cable Pulling':          ('2026-07-29', '2026-07-28'),
        'Termination':            (None,         '2026-08-02'),
        'Faceplate Installation': (None,         '2026-08-04'),
        'Testing':                (None,         '2026-08-06'),
    },
}

results = []


def check(name, ok, actual, expected):
    results.append((name, ok, actual, expected))


def fmt_dt(v):
    if v is None:
        return None
    if isinstance(v, datetime):
        return v.strftime('%Y-%m-%d')
    return str(v)


def main():
    assert os.path.exists(OUTPUT), f'Output file not found: {OUTPUT}'
    wb = openpyxl.load_workbook(OUTPUT)

    # ---- 1. Sheets present ----
    expected_sheets = ['Progress Report', 'Site Photo', 'Issue_RFA Log']
    check('Sheets present', wb.sheetnames == expected_sheets,
          wb.sheetnames, expected_sheets)

    # ===================== Progress Report =====================
    ws = wb['Progress Report']

    # Metadata
    check('PR E9 date', ws['E9'].value == '2026-07-30', ws['E9'].value, '2026-07-30')
    check('PR E10 project', ws['E10'].value == 'Aurora Tech Shanghai - L28 Smart Office Retrofit',
          ws['E10'].value, 'Aurora Tech Shanghai - L28 Smart Office Retrofit')

    # Row 13 phase headers (4 phases, each merged 3 cols starting at C=3)
    for i, phase in enumerate(EXPECTED_PHASES):
        col_idx = 3 + i * 3
        from openpyxl.utils import get_column_letter
        col = get_column_letter(col_idx)
        check(f'PR phase[{i}] header', ws[f'{col}13'].value == phase,
              ws[f'{col}13'].value, phase)
        # extra phase cols (O-W) should be empty at row 13
    extra_phase_headers_empty = all(
        ws.cell(row=13, column=c).value is None
        for c in range(15, 24)
    )
    check('PR extra phase headers empty', extra_phase_headers_empty, extra_phase_headers_empty, True)

    # Floor row
    check('PR floor B16', ws['B16'].value == 'L28', ws['B16'].value, 'L28')

    # Sub-items (rows 17-19) + progress data + font color + X formula
    for i, sub in enumerate(EXPECTED_SUBS):
        row = 17 + i
        check(f'PR sub[{i}] no', ws.cell(row=row, column=1).value == i + 1,
              ws.cell(row=row, column=1).value, i + 1)
        check(f'PR sub[{i}] name', ws.cell(row=row, column=2).value == sub,
              ws.cell(row=row, column=2).value, sub)
        for j, phase in enumerate(EXPECTED_PHASES):
            base = 3 + j * 3
            pct_cell = ws.cell(row=row, column=base)
            exp_pct, exp_status = EXPECTED_PROGRESS[sub][phase]
            check(f'PR {sub}/{phase} pct',
                  abs((pct_cell.value or 0) - exp_pct) < 1e-9,
                  pct_cell.value, exp_pct)
            font_color = pct_cell.font.color.rgb if pct_cell.font and pct_cell.font.color else None
            check(f'PR {sub}/{phase} fontcolor',
                  font_color == STATUS_COLOR[exp_status],
                  font_color, STATUS_COLOR[exp_status])
            # number format 0%
            check(f'PR {sub}/{phase} nf',
                  pct_cell.number_format == '0%', pct_cell.number_format, '0%')
            # Till / Target dates
            till_cell = ws.cell(row=row, column=base + 1)
            tgt_cell = ws.cell(row=row, column=base + 2)
            exp_till, exp_tgt = EXPECTED_DATES[sub][phase]
            check(f'PR {sub}/{phase} till',
                  fmt_dt(till_cell.value) == exp_till,
                  fmt_dt(till_cell.value), exp_till)
            check(f'PR {sub}/{phase} target',
                  fmt_dt(tgt_cell.value) == exp_tgt,
                  fmt_dt(tgt_cell.value), exp_tgt)
        # X column AVERAGE formula
        x_cell = ws.cell(row=row, column=24)
        exp_formula = '=AVERAGE(C{0},F{0},I{0},L{0})'.format(row)
        check(f'PR {sub} X formula',
              x_cell.value == exp_formula, x_cell.value, exp_formula)

    # Row 20 (4th sub-item) cleared
    row20_empty = all(
        ws.cell(row=20, column=c).value is None for c in range(1, 25)
    )
    check('PR row20 cleared', row20_empty, row20_empty, True)

    # X13 Overall Percentage header preserved
    check('PR X13 header', ws['X13'].value == 'Overall Percentage',
          ws['X13'].value, 'Overall Percentage')

    # Overall row 23 keeps % averages for 4 phases + X23 formula
    for j in range(len(EXPECTED_PHASES)):
        base = 3 + j * 3
        col = get_column_letter(base)
        f = ws[f'{col}23'].value
        check(f'PR overall {col}23 avg formula',
              isinstance(f, str) and f.startswith('=AVERAGE('),
              f, '=AVERAGE(...)')
    x23 = ws['X23'].value
    check('PR X23 avg formula', isinstance(x23, str) and x23.startswith('=AVERAGE('),
          x23, '=AVERAGE(...)')

    # ===================== Site Photo =====================
    ws2 = wb['Site Photo']
    check('SP D9 date', ws2['D9'].value == '2026-07-30', ws2['D9'].value, '2026-07-30')
    check('SP D10 project', ws2['D10'].value == 'Aurora Tech Shanghai - L28 Smart Office Retrofit',
          ws2['D10'].value, 'Aurora Tech Shanghai - L28 Smart Office Retrofit')

    expected_photos = [
        'Before cable pulling / 穿线前',
        'Cable pulling completed / 穿线完成',
        'Termination in progress / 端接过程',
        'Termination completed / 端接完成',
        'Before cable pulling / 穿线前',
        'Cable pulling completed / 穿线完成',
        'Before cable pulling / 穿线前',
    ]
    for i, desc in enumerate(expected_photos):
        row = 13 + i
        check(f'SP row{i} no', ws2.cell(row=row, column=1).value == i + 1,
              ws2.cell(row=row, column=1).value, i + 1)
        b = ws2.cell(row=row, column=2)
        check(f'SP row{i} date', fmt_dt(b.value) == '2026-07-30',
              fmt_dt(b.value), '2026-07-30')
        check(f'SP row{i} desc', ws2.cell(row=row, column=3).value == desc,
              ws2.cell(row=row, column=3).value, desc)
    # Rows 20-23 cleared
    rows_cleared = all(
        ws2.cell(row=r, column=c).value is None
        for r in range(20, 24) for c in range(1, 5)
    )
    check('SP rows 20-23 cleared', rows_cleared, rows_cleared, True)

    # ===================== Issue_RFA Log =====================
    ws3 = wb['Issue_RFA Log']

    # Metadata C11
    check('IRL C11 project', ws3['C11'].value == 'Aurora Tech Shanghai - L28 Smart Office Retrofit',
          ws3['C11'].value, 'Aurora Tech Shanghai - L28 Smart Office Retrofit')

    # Issue row 14
    check('IRL issue A14', ws3['A14'].value == 1, ws3['A14'].value, 1)
    check('IRL issue B14 date', fmt_dt(ws3['B14'].value) == '2026-07-29',
          fmt_dt(ws3['B14'].value), '2026-07-29')
    check('IRL issue C14 desc',
          ws3['C14'].value == 'Meeting Room cable tray routing conflicts with existing HVAC duct',
          ws3['C14'].value, 'Meeting Room cable tray routing conflicts with existing HVAC duct')
    check('IRL issue E14 risk', ws3['E14'].value == 'Medium', ws3['E14'].value, 'Medium')
    check('IRL issue F14 solution',
          ws3['F14'].value == 'Coordinate with MEP to reroute tray, propose alternative by 2026-07-31',
          ws3['F14'].value, '...')
    check('IRL issue G14 action_by', ws3['G14'].value == 'Cailleach',
          ws3['G14'].value, 'Cailleach')
    check('IRL issue I14 status', ws3['I14'].value == 'Open', ws3['I14'].value, 'Open')
    i14_fill = ws3['I14'].fill
    i14_fg = i14_fill.fgColor.rgb if i14_fill and i14_fill.fgColor else None
    check('IRL issue I14 fill (Open=orange)', i14_fg == 'FFFFC000', i14_fg, 'FFFFC000')

    # Rows 15-17 cleared
    for r in range(15, 18):
        check(f'IRL row{r} cleared',
              all(ws3.cell(row=r, column=c).value is None for c in [1, 3, 5, 6, 7, 9]),
              [ws3.cell(row=r, column=c).value for c in [1, 3, 5, 6, 7, 9]], 'all None')

    # RFA title row 18 + project row 20 + header row 22 preserved
    check('IRL A18 RFA title', ws3['A18'].value == 'RFI / RFA LOG',
          ws3['A18'].value, 'RFI / RFA LOG')
    check('IRL C20 project', ws3['C20'].value == 'Aurora Tech Shanghai - L28 Smart Office Retrofit',
          ws3['C20'].value, 'Aurora Tech Shanghai - L28 Smart Office Retrofit')
    check('IRL A22 header', ws3['A22'].value == 'Item No.', ws3['A22'].value, 'Item No.')
    check('IRL C22 header', ws3['C22'].value == 'RFI / RFA', ws3['C22'].value, 'RFI / RFA')

    # RFA row 23
    check('IRL rfa A23', ws3['A23'].value == 1, ws3['A23'].value, 1)
    check('IRL rfa B23 date', fmt_dt(ws3['B23'].value) == '2026-07-30',
          fmt_dt(ws3['B23'].value), '2026-07-30')
    check('IRL rfa C23 type', ws3['C23'].value == 'RFI', ws3['C23'].value, 'RFI')
    check('IRL rfa E23 desc',
          ws3['E23'].value == 'Request confirmation of final faceplate color (white vs ivory)',
          ws3['E23'].value, '...')
    check('IRL rfa F23 issued_to', ws3['F23'].value == 'Aurora Tech PM',
          ws3['F23'].value, 'Aurora Tech PM')
    check('IRL rfa G23 respond_by', fmt_dt(ws3['G23'].value) == '2026-08-02',
          fmt_dt(ws3['G23'].value), '2026-08-02')
    check('IRL rfa I23 status', ws3['I23'].value == 'Open', ws3['I23'].value, 'Open')
    i23_fill = ws3['I23'].fill
    i23_fg = i23_fill.fgColor.rgb if i23_fill and i23_fill.fgColor else None
    check('IRL rfa I23 fill (Open=orange)', i23_fg == 'FFFFC000', i23_fg, 'FFFFC000')

    # ---- Print results ----
    print('\n=== Verification ===')
    all_pass = True
    for name, ok, actual, expected in results:
        status = 'PASS' if ok else 'FAIL'
        if not ok:
            all_pass = False
        print(f'{status} | {name} | actual={actual!r} | expected={expected!r}')

    pass_n = sum(1 for _, ok, _, _ in results if ok)
    fail_n = sum(1 for _, ok, _, _ in results if not ok)
    print(f'\nTotal: {len(results)} | Pass: {pass_n} | Fail: {fail_n}')
    print(f'Overall: {"PASS" if all_pass else "FAIL"}')


if __name__ == '__main__':
    main()
